import { emitYaml, type YamlValue } from './yaml-emit.js';
import { DEFAULT_REPO_URL, type CiscoSignature, type SignatureFile } from './transform.js';

export const FILE_TYPES_ANCHOR = 'id001';

export interface RenderContext {
  readonly version: string;
  readonly repoUrl: string;
  /** Human sentence describing benchmark claims, already version-pinned. */
  readonly benchmarkSentence: string;
  readonly benchmarkReadmeLine: string;
  /**
   * Reproduce the banner comments of the pack currently vendored downstream,
   * quirks included: it names a converter that never lived in this repository,
   * and its per-file "N rules" count counts rule files in the category
   * directory rather than signatures emitted, so any category holding an
   * excluded rule is over-counted by one. Only for byte-for-byte verification;
   * a real export writes the corrected banner.
   */
  readonly reproduceVendored?: boolean;
  readonly filesPerCategory?: Readonly<Record<string, number>>;
}

const CATEGORY_LABELS: Readonly<Record<string, string>> = {
  agent_manipulation: 'Agent manipulation (multi-agent, autonomy)',
  context_exfiltration: 'Context exfiltration',
  data_poisoning: 'Data poisoning',
  excessive_autonomy: 'Excessive autonomy',
  model_abuse: 'Model abuse',
  model_security: 'Model security',
  privilege_escalation: 'Privilege escalation',
  prompt_injection: 'Prompt injection',
  skill_compromise: 'Skill compromise',
  tool_poisoning: 'MCP tool poisoning',
};

function signatureNode(signature: CiscoSignature): Record<string, YamlValue> {
  return {
    id: signature.id,
    atr_id: signature.atr_id,
    atr_url: signature.atr_url,
    category: signature.category,
    severity: signature.severity,
    // Present unless the export is reproducing the pack vendored downstream,
    // which predates the field.
    ...(signature.maturity ? { maturity: signature.maturity } : {}),
    patterns: [...signature.patterns],
    file_types: [...signature.file_types],
    description: signature.description,
    remediation: signature.remediation,
  };
}

const VENDORED_GENERATOR = 'convert-to-skill-scanner.mjs';
const GENERATOR = 'scripts/export-cisco-pack.ts';

function headerCount(file: SignatureFile, context: RenderContext): number {
  if (context.reproduceVendored) {
    const seen = context.filesPerCategory?.[file.category];
    if (typeof seen !== 'number') throw new Error(`no file count for category ${file.category}`);
    return seen;
  }
  return file.signatures.length;
}

export function renderSignatureFile(file: SignatureFile, context: RenderContext): string {
  const count = headerCount(file, context);
  const generator = context.reproduceVendored ? VENDORED_GENERATOR : GENERATOR;
  const banner = [
    `# ATR (Agent Threat Rules) — ${file.category} signatures`,
    `# Source: ${context.repoUrl}`,
    `# ATR v${context.version} · ${count} rules · MIT License`,
    `# Auto-generated by ${generator} — do not edit manually`,
    '',
  ].join('\n');
  const body = emitYaml(
    { signatures: file.signatures.map(signatureNode) },
    { anchoredKeys: { file_types: FILE_TYPES_ANCHOR } },
  );
  return banner + body;
}

function packDescription(total: number, categories: number, context: RenderContext): string {
  const names =
    'prompt injection, agent manipulation, skill compromise, context exfiltration, ' +
    'tool poisoning, privilege escalation, model abuse, excessive autonomy, ' +
    'data poisoning, and model security';
  return (
    `Open-source AI agent security detection rules from the Agent Threat Rules (ATR) project. ` +
    `${total} supported static rules across ${categories} attack categories: ${names}. ` +
    `${context.benchmarkSentence} MIT license.`
  );
}

/**
 * The shape the vendored pack ships today: a nested `pack:` block and a
 * `rules:` sequence. PackLoader.load_pack reads `name`/`version`/
 * `description` from the top level and calls `.items()` on `rules`, so this
 * shape loses all three and raises AttributeError on the sequence. Kept only
 * to prove byte-for-byte reproduction of what is already vendored.
 */
function renderLegacyManifest(files: readonly SignatureFile[], context: RenderContext): string {
  const total = files.reduce((sum, file) => sum + file.signatures.length, 0);
  const banner = [
    '# ATR (Agent Threat Rules) Rule Pack for Cisco Skill Scanner',
    `# Source: ${context.repoUrl}`,
    `# Version: ${context.version}`,
    `# Supported ATR static ruleset: ${total} rules across ${files.length} attack categories.`,
    `# MIT License. Auto-indexed from ${files.length} category signature files.`,
    '',
    '',
  ].join('\n');
  const rules: YamlValue[] = files.flatMap((file) =>
    file.signatures.map((signature) => ({
      atr_id: signature.atr_id,
      category: signature.category,
      description: signature.description,
      file: file.path,
      id: signature.id,
      severity: signature.severity,
    })),
  );
  return (
    banner +
    emitYaml({
      pack: {
        id: 'atr',
        name: 'ATR Agent Threat Rules',
        version: context.version,
        description: packDescription(total, files.length, context),
        author: 'ATR Community',
        license: 'MIT',
        source_url: context.repoUrl,
        signature_files: files.map((file) => file.path),
      },
      rules,
    })
  );
}

/**
 * The shape PackLoader.load_pack actually reads: top-level `name`, `version`
 * and `description`, and `rules` as a mapping keyed by rule id, each entry
 * carrying `source`, `category`, `severity`, `knobs.enabled`, `description`
 * and `remediation` — matching skill_scanner/data/packs/core/pack.yaml.
 * `atr_id`, `atr_url` and `file` are extra keys the loader ignores; they keep
 * the provenance the previous index carried.
 */
export function renderPackManifest(files: readonly SignatureFile[], context: RenderContext): string {
  if (context.reproduceVendored) return renderLegacyManifest(files, context);
  const total = files.reduce((sum, file) => sum + file.signatures.length, 0);
  const banner = [
    '# ATR (Agent Threat Rules) Rule Pack for Cisco Skill Scanner',
    `# Source: ${context.repoUrl}`,
    `# Version: ${context.version}`,
    `# Supported ATR static ruleset: ${total} rules across ${files.length} attack categories.`,
    `# MIT License. Auto-generated by ${GENERATOR} — do not edit manually.`,
    '',
    '',
  ].join('\n');
  const rules: Record<string, YamlValue> = {};
  for (const file of files) {
    for (const signature of file.signatures) {
      rules[signature.id] = {
        source: 'signature',
        category: signature.category,
        severity: signature.severity,
        ...(signature.maturity ? { maturity: signature.maturity } : {}),
        knobs: { enabled: true },
        description: signature.description,
        ...(signature.remediation ? { remediation: signature.remediation } : {}),
        atr_id: signature.atr_id,
        atr_url: signature.atr_url,
        file: file.path,
      };
    }
  }
  return (
    banner +
    emitYaml({
      name: 'atr',
      version: context.version,
      description: packDescription(total, files.length, context),
      author: 'ATR Community',
      license: 'MIT',
      source_url: context.repoUrl,
      signature_files: files.map((file) => file.path),
      rules,
    })
  );
}

function categoryRow(file: SignatureFile): string {
  const label = CATEGORY_LABELS[file.signatures[0]?.category ?? ''] ?? file.category;
  return `| \`${file.path}\` | ${label} | ${file.signatures.length} |`;
}

export function renderReadme(
  files: readonly SignatureFile[],
  context: RenderContext,
  excluded: readonly { readonly id: string; readonly reason: string }[],
): string {
  const total = files.reduce((sum, file) => sum + file.signatures.length, 0);
  const ordered = [...files].sort((a, b) => b.signatures.length - a.signatures.length);
  const exclusionNote =
    excluded.length === 0
      ? 'Every rule in the ATR release is representable as a static signature.'
      : `${excluded.length} rule(s) in the ATR release are not representable as static ` +
        `signatures and are excluded: ${excluded.map((e) => `\`${e.id}\` (${e.reason})`).join(', ')}. ` +
        'A signature pack matches regular expressions against file content; it cannot ' +
        'evaluate a per-session time window or a tool-call count.';
  return `# ATR Rule Pack for Cisco Skill Scanner

**Source:** [Agent Threat Rules (ATR)](${context.repoUrl})
**ATR Version:** ${context.version}
**Rules:** ${total} signatures across ${files.length} signature files
**License:** MIT
**Benchmarks:** ${context.benchmarkReadmeLine}

## Overview

This pack adds AI-agent security detection rules from the open-source ATR
project, covering attack surfaces specific to modern AI-agent deployments
(MCP tool layer, multi-agent trust, skill manifests, agent autonomy). It is
the current ATR \`${context.version}\` static ruleset. ${exclusionNote}

## Attack Categories

| Signature file | Category | Rules |
|---|---|---|
${ordered.map(categoryRow).join('\n')}
| **Total** | **${files.length} categories** | **${total}** |

The full per-rule index (ATR id, category, severity, signature file) lives in
\`pack.yaml\`. Each signature carries an \`atr_url\` linking to the source rule
YAML on GitHub.

## File Structure

\`\`\`text
skill_scanner/data/packs/atr/
├── pack.yaml            # Pack manifest — indexes all ${total} rules
├── README.md            # This file
└── signatures/          # ${files.length} category signature files (atr_<category>.yaml)
\`\`\`

## Pattern Provenance

All regex patterns are extracted verbatim from ATR YAML rule files
(\`detection.conditions[].value\`). No patterns were invented for this pack.
Every signature records its originating ATR rule id and a direct link to the
source YAML.

## How this pack is generated

This pack is produced by \`scripts/export-cisco-pack.ts\` in the ATR
repository, so a refresh is a re-run rather than a hand edit. The exporter is
covered by a test that regenerates the previously shipped pack and compares it
byte-for-byte, which is what keeps schema drift from reaching this directory.

## Staying current

ATR publishes stability guarantees for downstream consumers in its
[Downstream Sync Contract](${context.repoUrl}/blob/main/docs/DOWNSTREAM-SYNC-CONTRACT.md)
(permanent rule ids, no silent removal of stable rules, a public
false-positive reporting channel). Consumers that want only the
highest-confidence tier can filter to \`maturity: stable\`.

## ATR Project Links

- Repository: ${context.repoUrl}
- License: MIT
`;
}

export const DEFAULT_CONTEXT_REPO_URL = DEFAULT_REPO_URL;
